version: '3.4'

networks:
  wmwnet: {}

services:
  traefik:
    image: "traefik:v2.11"
    container_name: traefik-proxy
    command:
      #- --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # - --providers.docker.network=wmwnet
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - 80:80
      - 8080:8080
      - 443-443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - wmwnet
  
  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    labels:
      # - --port=3000
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`localhost`)
      - traefik.http.routers.whoami.entrypoints=web
      # - traefik.http.services.whoami.loadbalancer.server.port=80
    networks:
      - wmwnet

  backend:
    image: watchmywatch/repo:backend
    container_name: backend
    # restart: on-failure
    # build:
      # context: ./
      # dockerfile: Dockerfile #Dockerfile-prod
    # environment:
    #   DATABASE_NAME: watchmywatch
      # DATABASE_USER: watchmywatch
      # DATABASE_PASS: hctawymhctaw
      # DATABASE_URI: mongodb://database:27017
    environment:
      - PORT=3002
    ports:
      - 3002:3002
    networks:
      - wmwnet
    labels:
      # - --port=3002
      - traefik.enable=true
      - traefik.docker.network=wmwnet
      # - traefik.http.routers.backend.rule=Host(`test.mydomain.com`)
      - traefik.http.routers.backend.rule=Host(`localhost`)
      # - traefik.http.routers.backend.entrypoints=web
      - traefik.http.services.backend.loadbalancer.server.port=3002
      - traefik.http.services.backend.loadbalancer.sticky=true
      
  frontadmin:
    image: watchmywatch/repo:frontendadmin
    container_name: frontadmin
    # restart: always
    # build:
      # context: .
      # dockerfile: ./Dockerfile
    # environment:
      # NODE_ENV: production
    environment:
      - PORT=3001
    ports:
      - 3001:3001 #80:3001
    networks:
      - wmwnet
    labels:
      # - --port=3001
      - traefik.enable=true
      - traefik.docker.network=wmwnet
      #- traefik.http.routers.frontadmin.rule=Host(`test.mydomain.com`)
      - traefik.http.routers.frontadmin.rule=Host(`localhost`)
      - traefik.http.routers.frontadmin.entrypoints=web
      - traefik.http.services.frontadmin.loadbalancer.server.port=3001
      - traefik.http.services.frontadmin.loadbalancer.sticky=true
      
  frontend:
    image: watchmywatch/repo:frontend
    container_name: frontend
    # restart: always
    # build:
      # context: .
      # dockerfile: ./Dockerfile
    # environment:
      # NODE_ENV: production
    environment:
      - PORT=3000
    ports:
      - 3000:3000 #80:3000
    networks:
      - wmwnet
    labels:
      # - --port=3000
      - traefik.enable=true
      - traefik.docker.network=wmwnet
      # - traefik.http.routers.frontend.rule=Host(`test.mydomain.com`)
      - traefik.http.routers.frontend.rule=Host(`localhost`)
      - traefik.http.routers.frontend.entrypoints=web
      - traefik.http.services.frontend.loadbalancer.server.port=3000
      - traefik.http.services.frontend.loadbalancer.sticky=true
